<?php
/**
 * Created by PhpStorm.
 * User: tkachukvital
 * Date: 01.11.2017
 * Time: 15:14
 */

class Model_testimonials extends Model
{

    private $id;
    private $id_user;
    private $testimonial;
    private $date;

    public function getTable()
    {
        return $table = 'testimonials';
    }

    public function getFields(){
        return  $getFields = array('id_user', 'testimonials', 'date');
    }
    public function getAllRows($table)
    {
        return parent::getAllRows(); // TODO: Change the autogenerated stub
    }


    public function setInsertTestimonials($db, $post)
    {
        $query = $db->prepare("INSERT INTO testimonials (id_user, testimonial, date)
        VALUES(:id_user, :testemonial, :date)");
        $query->execute(array(
            "id_user" => "2",
            "testemonial" => $post['testimonials'],
            "date" => date('Y-m-d H:i:s')

        ));
    }


}
